### PR TITLE
Type information stored in gct files, with tests

### PR DESCRIPTION
**Pull request by reid47**
Edited xmodule to retain type information in the gct file
for a compiled program. Added tests of this in tests/ and
js/tests/. Includes type expressions with & and |.

### CODE REVIEW

**Comment by apblack** [comment]
I'm in the process of merging this.   It's an impressive piece of work!  I've been puzzling over the meaning of the numbers, as with the `2`in 
```
 :2 m1(n : Number) -> Number
 :2 m2(n : Number) -> Done
```
I'm assuming that the numbers identify anonymous types, but `2` appears in three places.   Presumably the scope of the numbers is limited to a single `methodtypes-of` entry?

And why is it necessary to prefix each line with `<space>:` rather than just `<space>`?

I'm asking these questions because one day I will probably have to maintain this code, and I want to understand it!  Putting a description of the format in the _doc_ directory would be a big help.  Yes, I know that the original format wasn't documented, but we are trying to improve matters, not make things worse!

**Comment by reid47** [comment]
Sure, I can write documentation for this. The numbers do identify anonymous types. They're helpful when trying to rebuild types that look like:
```
    type Z = type {
        m4(x:Y) -> Y
    } & type {
        m5(x:Z) -> Z
    }
```
The values of the numbers don't matter, but for consistency I'll use 3 and 4, which is what they are in the test file. The important thing is that Z will be represented as `&3` and `&4`, which means a combination of two type-literals (`3` and `4`) with &. So all methodtypes that come from the `3` type-literal will be listed with a `3`.

```
methodtypes-of:Z:
 :& 3
 :& 4
 :3 m4(x : Y) -> Y
 :4 m5(x : Z) -> Z
```
If we just listed all the methodtypes without an identifying number, when "rebuilding" the types later I could merge both `m4` and `m5` into the same list of methodtypes to create an ObjectType that has both of these methods. But if the two type-literals were combined with `|`, I could not merge `m4` and `m5` into the same list; it would have to be built into a type with either m4 or m5 (not both). So we use the numbers to keep the two type-literals distinct in the gct, so they can be rebuilt into a union type of two type-literals, rather than a simple type of one merged type-literal. Since the rest of the gct was strictly two levels of indentation, I didn't want to add a third level (something like methodtypes-of -> typeliteral -> methodtypes-of-literal).

I realize now that the `:` could be removed. Before I developed the above system for identifying type-literals, the line for a methodtype began with just the method name, so I wanted to insert a character that was illegal for the start of method names. Some types do have a method that starts with `&` or `|` (for example, in `staticTypes`, these are methods used for creating a union ObjectType out of two ObjectTypes), so I put a `:` before the method name. Now, though, every line under `methodtypes-of` starts with either `:|`, `:&`, or `:{some number}`. So the `:` is unnecessary. I could remove it and commit the changes, if you want.

**Comment by apblack** [comment]
why not remove the `:`.  It doesn't matter now, but we'll forever be wondering about it if you leave it there!

**Comment by reid47** [comment]
Just removed it and pushed the changes.

**Comment by apblack** [comment]
And the changes are in master.   Before you forget, please write a description of the gct and put it in a file in /doc.  The contents of your previous comment are probably all that�s necessary.

**Pull request merged**
