### PR TITLE
Type information stored in gct files

### PR DESCRIPTION
**Pull request by reid47**
I've modified xmodule.grace so that it preserves information about types declared in a file. When a .grace file is compiled, its .gct now includes a "types" section which lists the names of all the types declared within, and for each type a "methodtypes-of" section, which lists the methodtype signatures of all the methods within that type.

### CODE REVIEW

**Comment by apblack** [comment]
Ryan,
I want to try this out, but I don't see how I can merge this.  I have to admit to not being a git expert.  It seems that the only changes that you have made are to module, but git shows 12 commit to various files ...

Can you make me a single commit or series of commits that can be applied to the current xmodule?

With regard to the content, I think that it would be much easier to read if you created your visitor outside of generateGCT, and use it inside.  Did you test it on, say, collectionsPrelude?  It looks as if you are only visiting typeLiterals, but the right-hand-side of a typedef can be an arbitrary type expression, for example, involving & and |.

**Comment by reid47** [comment]
Thanks for the feedback. Sorry about the 12 commits - I am not a git expert either, and I accidentally created those while trying to merge my code with the rest. I didn’t realize that they would all get added if you pulled my last commit in. I am working on making the code more readable, as you suggested, and handling type expressions. Once that is done and tested, I’ll submit another pull request (this time with only the commits that change xmodule).

- Reid

On Jul 21, 2015, at 12:12 AM, Andrew Black <notifications@github.com<mailto:notifications@github.com>> wrote:


Ryan,
I want to try this out, but I don't see how I can merge this. I have to admit to not being a git expert. It seems that the only changes that you have made are to module, but git shows 12 commit to various files ...

Can you make me a single commit or series of commits that can be applied to the current xmodule?

With regard to the content, I think that it would be much easier to read if you created your visitor outside of generateGCT, and use it inside. Did you test it on, say, collectionsPrelude? It looks as if you are only visiting typeLiterals, but the right-hand-side of a typedef can be an arbitrary type expression, for example, involving & and |.

**Comment by apblack** [comment]
On 21 Jul 2015, at 11:14 , Reid Mitchell <notifications@github.com> wrote:

> Thanks for the feedback. Sorry about the 12 commits - I am not a git expert either, and I accidentally created those while trying to merge my code with the rest. I didn’t realize that they would all get added if you pulled my last commit in.

So, what I should do is CLOSE the previous pull request, and let you create a new one.  The new one should be "based" on the then-current gracelang/master.  I'll do that.

> I am working on making the code more readable, as you suggested, and handling type expressions. Once that is done and tested, I’ll submit another pull request (this time with only the commits that change xmodule). 

The compiler currently generates executable code for type expressions.  So one way to evaluate them would be to load the generated code.   Then what you would put in the gct file would be the name of the method to request to get the type value.    This would require making all modules dynamically loadable — currently the compiler supports statically loadable and dynamically loadable modules, but this is mostly historical, and I don't see any reason why we shouldn't make them all dynamically loadable all the time.   (But I may be wrong!)

An alternative would be to essentially interpret the types at the same time that we compile them.   Essentially, this would mean adding "eval" methods (or visitor) on the AST, so that a type expressions like ( A & B ) would be both compiled into executable code, and interpreted.   The issue here would be making sure that the two meanings are consistent.

Types are currently represented as sets of method names.  This is fine for most purposes, like &, but not for |.  Prof Bruce needs to come up with a model for types that takes | into account.  [My choice would be to eliminate | from the language, and just have meet (method-set intersection) and join (method-set union).  But they aren't asking me!]   Independent of whether you interpret or execute the type expressions, you will still need a way of representing the answers!

Tests are key!  Write some tests not only for

	 type name = typeLiteral & typeLiteral

but also for 

	type name = typeName & typeName
	type name = typeLiteral & (typeLiteral + typeExpression)
	type name = typeLiteral + (typeName & typeName)

and for the variants with | too, once the rules for combining them are clear.

	Andrew

> - Reid 
>

**Comment by apblack** [comment]
I'm closing this pull request, and hope that you soon submit another with just the right commits and tests.

**Pull request closed without merging**
